version : "3.5"

volumes :
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/zack/Desktop/Inception_42/y(worked)/srcs/maria
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/zack/Desktop/Inception_42/y(worked)/srcs/nemi
      o: bind
      type: none

networks:
  inception:
    name: "inception"
    driver: "bridge"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:v1
    build:
      context: ./requirements/mariadb/.
      args :
        - db_name=zezzine
        - db_user=zack
        - db_pass=123
    volumes:
      - mariadb:/var/lib/mysql/
    env_file: .env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress:v1
    build: 
      context: ./requirements/wordpress/.
      args :
        - db_name=zezzine
        - db_user=zack
        - db_pass=123
        - TITLE=title1
        - DOMAIN_NAME=zezzine.42.fr
        - ADMIN_U=name
        - ADMIN_P=1234
        - ADMIN_MAIL=zack.zezzine@gmail.com
        - WP_USR=zack12
        - PASSWORD_USR=123
        - WP_EMAIL=zezzine@student.1337.ma
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html/
    env_file: .env
    networks:
      - inception
  
  nginx:
    container_name: nginx
    image: nginx:v1
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception

  redis:
    container_name: redis
    image: redis:v1
    build: ./requirements/bonus/redis/.
    ports: 
      - "6379:6379"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  website-static:
    container_name: static-web
    image: static-web:v1
    build:
      context: ./requirements/bonus/static-web/.
    ports: 
      - "2001:2001"
    networks:
      - inception
    restart: always

  cadvisor:
    container_name: cadvisor
    image: cadvisor:v1
    build: 
      context: ./requirements/bonus/cadvisor/.
    ports:
      - "8080:8080"
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

  adminer:
    container_name: adminer
    image: adminer:v1
    build:
      context: ./requirements/bonus/Adminer/.
    ports:
      - "8888:8888"
    networks:
      - inception
    restart: always